# Generated by Django 3.2.6 on 2021-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='display_name',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
