# Generated by Django 3.2.6 on 2021-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email_form',
            field=models.EmailField(max_length=50),
        ),
    ]
