# Generated by Django 3.2.6 on 2021-09-13 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='body',
            field=models.CharField(default='', max_length=2056),
        ),
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 20, 12, 23, 841430, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email_to',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
