# Generated by Django 3.2.6 on 2021-10-23 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20211019_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 13, 54, 19, 605231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='response_time',
            field=models.PositiveSmallIntegerField(help_text='in milliseconds.'),
        ),
    ]
