# Generated by Django 3.2.6 on 2021-11-17 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_auto_20211023_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='responselog',
            name='request_method',
            field=models.CharField(choices=[('GET', 'get'), ('POST', 'post')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 14, 55, 34, 123559, tzinfo=utc)),
        ),
    ]
