# Generated by Django 3.2.6 on 2021-10-23 19:29

from django.db import migrations
from currency import model_choices as mch


def forwards(apps, schema_editor):
    Rate = apps.get_model('currency', 'Rate')
    for rate in Rate.objects.all().only('type'):
        if 'usd' in rate.type.lower():
            rate.type = mch.TYPE_USD
        elif 'eur' in rate.type.lower():
            rate.type = mch.TYPE_EUR
        else:
            rate.type = mch.TYPE_USD

        rate.save(update_fields=('type',))

    Request = apps.get_model('currency', 'ResponseLog')
    for request in Request.objects.all().only('response_log'):
        if 'get' in request.type.lower():
            request.type = mch.REQUEST_GET
        elif 'post' in request.type.lower():
            request.type = mch.REQUEST_POST
        else:
            request.type = mch.REQUEST_GET

        request.save(update_fields=('response_log',))


def backwards(apps, schema_editor):
    print('backwards \n' * 10)


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0009_auto_20211023_1354'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
