# Generated by Django 3.2.6 on 2021-12-15 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_auto_20211117_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 14, 11, 39, 430116, tzinfo=utc)),
        ),
    ]
