# Generated by Django 3.2.6 on 2021-11-03 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_auto_20211023_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='responselog',
            name='response_log',
            field=models.CharField(choices=[('GET', 'get'), ('POST', 'post')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 12, 26, 38, 483025, tzinfo=utc)),
        ),
    ]
