# Generated by Django 3.2.6 on 2021-11-03 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_auto_20211103_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 15, 8, 18, 168461, tzinfo=utc)),
        ),
    ]
