# Generated by Django 3.2.6 on 2021-11-03 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_alter_contactus_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responselog',
            old_name='response_log',
            new_name='request_method',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 16, 34, 49, 254494, tzinfo=utc)),
        ),
    ]
